name: maplibre_gl
description: A Flutter plugin for integrating MapLibre Maps inside a Flutter application on Android, iOS and web platforms.
version: 0.24.1+1
publish_to: https://dart.cloudsmith.io/dronetag/software/
repository: https://github.com/dronetag/flutter-maplibre-gl
issue_tracker: https://github.com/dronetag/flutter-maplibre-gl/issues
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl_platform_interface:
    version: 0.24.1+1
    hosted: https://dart.cloudsmith.io/dronetag/software/
  maplibre_gl_web:
    version: 0.24.1+1
    hosted: https://dart.cloudsmith.io/dronetag/software/

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: maplibre_gl_web

platforms:
  android:
  ios:
  web:
